version: '3.5'

services:

  web:
    restart: always
    build: ./web
    image: sterneberg/image-converter-web
    ports:
      - 8000:8000
    networks:
      - front-tier
    deploy:
      replicas: 3
    update_config:
      parallelism: 2
      delay: 10s      
    command: 'gunicorn --worker-class gevent --workers 4 --bind :8000 app:application'

  nginx:
    restart: always
    build: ./nginx
    image: sterneberg/image-converter-nginx
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - front-tier

networks:
  front-tier:
    driver: overlay
